[tool.poetry]
name = "pytm"
version = "1.3.1"
description = "A Pythonic framework for threat modeling"
authors = ["pytm Team"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.11 || ^3.10 || ^3.9 || ^3.8"
pydal = "~20200714.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
